groups:
- name: example-alerts
  rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Инстанс недоступен"
        description: "Экземпляр ({{ $labels.instance }}) недоступен в течение 1 минуты"

    - alert: HighCPU
      expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "Высокая загрузка CPU"
        description: "CPU usage > 85% более 3 минут на {{ $labels.instance }}"
