services:
  fluentd:
    build: .
    container_name: fluentd
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf
      - ./logs:/var/log/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "24224:24224/tcp"
    restart: unless-stopped
    networks:
      - bridge
