include:
  - ./database/db-compose.yaml
  - rabbit_mq/rabbit-compose.yaml
  - fluentd/fluentd-compose.yaml


services:
  watchdog:
    build:
      context: ./watchdog
      dockerfile: Dockerfile
    container_name: cool_thing_watchdog
    restart: unless-stopped
    networks:
      - bridge
    volumes:
      - ./watchdog/tmp:/app/tmp
      - ./watchdog/settings.json:/app/settings.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      fluentd:
        condition: service_started
      db:
        condition: service_healthy
      queue:
        condition: service_healthy
    stop_grace_period: 2m
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: watchdog

networks:
  bridge:
    driver: bridge
    external: true
    name: coolthing_bridge
