include:
  - ./database/db-compose-side.yaml
  - rabbit_mq/rabbit-compose.yaml
  - fluentd/fluentd-compose.yaml
  - scripts_database/scripts-db-compose.yaml
  - monitoring-setup/compose.yaml


services:
#  watchdog:
#    build:
#      context: ./watchdog
#      dockerfile: Dockerfile
#    container_name: cool_thing_watchdog
#    restart: unless-stopped
#    networks:
#      - bridge
#    volumes:
#      - ./watchdog/tmp:/app/tmp
#      - ./watchdog/settings.json:/app/settings.json
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/localtime:/etc/localtime:ro
#    depends_on:
#      fluentd:
#        condition: service_started
#      db:
#        condition: service_healthy
#      queue:
#        condition: service_healthy
#    stop_grace_period: 2m
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: 127.0.0.1:24224
#        tag: watchdog
#  bot:
#    build:
#      context: ./bot
#      dockerfile: Dockerfile
#    container_name: cool_thing_bot
#    restart: unless-stopped
#    networks:
#      - bridge
#    volumes:
#      - ./bot/settings.json:/app/settings.json
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    depends_on:
#      fluentd:
#        condition: service_started
#      queue:
#        condition: service_healthy
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: 127.0.0.1:24224
#        tag: bot
#  scripts:
#    build:
#      context: ./scripts
#      dockerfile: Dockerfile
#    container_name: cool_thing_scripts
#    restart: unless-stopped
#    networks:
#      - bridge
#    volumes:
#      - ./scripts/settings.json:/app/settings.json
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    depends_on:
#      fluentd:
#        condition: service_started
#      queue:
#        condition: service_healthy
#      scripts-watcher:
#        condition: service_started
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: 127.0.0.1:24224
#        tag: scripts
  scripts-watchdog:
    build:
      context: ./scripts_watchdog
      dockerfile: Dockerfile
    container_name: cool_thing_scripts_watchdog
    restart: unless-stopped
    networks:
      - bridge
    volumes:
      - ./scripts_watchdog/settings.json:/app/settings.json
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts_watchdog/tmp:/app/tmp
    depends_on:
      fluentd:
        condition: service_started
      queue:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: scripts-watchdog
  scripts-watcher:
    build:
      context: ./scripts_watcher
      dockerfile: Dockerfile
    container_name: cool_thing_scripts_watcher
    restart: unless-stopped
    networks:
      - bridge
    volumes:
#      - ./scripts_watcher/settings.json:/app/settings.json
#      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      fluentd:
        condition: service_started
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: scripts-watcher
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: cool_thing_admin
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
#      - ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--root-path", "/admin"]
    restart: unless-stopped
    networks:
      - bridge
    volumes:
      - ./admin/settings.json:/app/settings.json
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      fluentd:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: admin
  notifier:
    build:
      context: ./notifier
      dockerfile: Dockerfile
    container_name: cool_thing_notifier
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped
    networks:
      - bridge
    volumes:
      - ./notifier/settings.json:/app/settings.json
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      fluentd:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8085:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: notifier
  metrics-worker:
    build: ./metrics_worker
    container_name: coolthing_metrics_app
    ports:
      - "8000:8080"
    networks:
      - default
      - monitoring
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: metrics-worker


networks:
  bridge:
    driver: bridge
    external: true
    name: coolthing_bridge
    attachable: true
