include:
  - ./database/db-compose.yaml
  - rabbit_mq/rabbit-compose.yaml
  - fluentd/fluentd-compose.yaml


services:
  watchdog:
    build:
      context: ./watchdog
      dockerfile: Dockerfile
    container_name: cool_thing_watchdog
    restart: unless-stopped
    networks:
      - bridge
    volumes:
      - ./watchdog/tmp:/app/tmp
      - ./watchdog/settings.json:/app/settings.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      fluentd:
        condition: service_started
      db:
        condition: service_healthy
      queue:
        condition: service_healthy
    stop_grace_period: 2m
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: watchdog
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: cool_thing_bot
    restart: unless-stopped
    networks:
      - bridge
    volumes:
      - ./bot/settings.json:/app/settings.json
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      fluentd:
        condition: service_started
      queue:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: bot
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: cool_thing_admin
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
#      - ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--root-path", "/admin"]
    restart: unless-stopped
    networks:
      - bridge
    volumes:
      - ./admin/settings.json:/app/settings.json
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      fluentd:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: admin

networks:
  bridge:
    driver: bridge
    external: true
    name: coolthing_bridge
    attachable: true
