from .dashboard import router as dashboard_router
from .bots import router as bots_router
from .bot import router as bot_router
from .fallback import router as fallback_router
from .prompts import router as prompts_router
from .chats import router as chats_router
from .campaigns import router as campaigns_router
from .gpt_settings import router as gpt_settings_router
from .auth import router as auth_router
