{
 "title": "Logs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "managerIDs",
    "query": {}
   },
   {
    "name": "parserIDs",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bot",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{tag_name=\"bot\"} | logfmt | line_format `{{.log}}`"
    }
   ]
  },
  {
   "title": "Admin",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{tag_name=\"admin\"} | logfmt | line_format `{{.log}}`"
    }
   ]
  },
  {
   "title": "Watchdog",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{tag_name=\"watchdog\"} | logfmt | line_format `{{.log}}`"
    }
   ]
  },
  { "title": "Managers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "${managerIDs}",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "repeat": "managerIDs",
   "targets": [
    {
     "expr": "{job=\"fluentd\"} | logfmt | container_name =~ `\\/tg-groups-manager-[[:print:]]*` | line_format `{{.log}}`"
    }
   ]
  },
  { "title": "Parsers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "${parserIDs}",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{job=\"fluentd\"} | logfmt | container_name =~ `\\/tg-groups-parser-[[:print:]]*` | line_format `{{.log}}`"
    }
   ]
  }
 ]
}