"""bundles

Revision ID: 1abbcf5859b7
Revises: e2f12ec275a0
Create Date: 2024-09-10 20:49:51.213842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abbcf5859b7'
down_revision: Union[str, None] = 'e2f12ec275a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots_bundles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_bundles_deleted_at'), 'bots_bundles', ['deleted_at'], unique=False)
    op.create_table('bots_bundles_mappings',
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['bundle_id'], ['bots_bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_bundles_mappings_deleted_at'), 'bots_bundles_mappings', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bots_bundles_mappings_deleted_at'), table_name='bots_bundles_mappings')
    op.drop_table('bots_bundles_mappings')
    op.drop_index(op.f('ix_bots_bundles_deleted_at'), table_name='bots_bundles')
    op.drop_table('bots_bundles')
    # ### end Alembic commands ###
