"""add deleted_At and idx

Revision ID: 1ca560c8f5b2
Revises: c2b7ff51ddca
Create Date: 2024-08-09 02:18:56.392863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca560c8f5b2'
down_revision: Union[str, None] = 'c2b7ff51ddca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_campaigns_deleted_at'), 'campaigns', ['deleted_at'], unique=False)
    op.add_column('chats', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_chats_deleted_at'), 'chats', ['deleted_at'], unique=False)
    op.add_column('gpt_settings', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_gpt_settings_deleted_at'), 'gpt_settings', ['deleted_at'], unique=False)
    op.add_column('messages', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.add_column('workers', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_workers_deleted_at'), 'workers', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_deleted_at'), table_name='workers')
    op.drop_column('workers', 'deleted_at')
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_column('messages', 'deleted_at')
    op.drop_index(op.f('ix_gpt_settings_deleted_at'), table_name='gpt_settings')
    op.drop_column('gpt_settings', 'deleted_at')
    op.drop_index(op.f('ix_chats_deleted_at'), table_name='chats')
    op.drop_column('chats', 'deleted_at')
    op.drop_index(op.f('ix_campaigns_deleted_at'), table_name='campaigns')
    op.drop_column('campaigns', 'deleted_at')
    # ### end Alembic commands ###
