"""nulls for campaign

Revision ID: 50876e6b5c16
Revises: d205b178bf6b
Create Date: 2024-09-28 12:08:21.738196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50876e6b5c16'
down_revision: Union[str, None] = 'd205b178bf6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'new_lead_wait_interval_seconds',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'180-300'::character varying"))
    op.alter_column('campaigns', 'chat_answer_wait_interval_seconds',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'15-30'::character varying"))
    op.alter_column('campaigns', 'welcome_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('campaigns', 'chats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('campaigns', 'plus_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('campaigns', 'minus_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('campaigns', 'gpt_settings_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'gpt_settings_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('campaigns', 'minus_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('campaigns', 'plus_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('campaigns', 'chats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('campaigns', 'welcome_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('campaigns', 'chat_answer_wait_interval_seconds',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'15-30'::character varying"))
    op.alter_column('campaigns', 'new_lead_wait_interval_seconds',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'180-300'::character varying"))
    # ### end Alembic commands ###
