"""think about nullable

Revision ID: 74bed66211d6
Revises: a77d819008d0
Create Date: 2024-08-01 03:54:10.546190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74bed66211d6'
down_revision: Union[str, None] = 'a77d819008d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('auto_reply', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('gpt_settings', 'assistant',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('gpt_settings', 'service_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('workers', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('workers', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workers', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('gpt_settings', 'service_prompt',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('gpt_settings', 'assistant',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chats', 'auto_reply')
    # ### end Alembic commands ###
