"""nullable workers.campaign_id

Revision ID: 7c9f127fa8de
Revises: 50876e6b5c16
Create Date: 2024-11-28 12:51:30.135915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9f127fa8de'
down_revision: Union[str, None] = '50876e6b5c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
