"""empty message

Revision ID: 8782b2d39173
Revises: 4b11c551e078
Create Date: 2024-07-14 23:05:09.405263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8782b2d39173'
down_revision: Union[str, None] = '4b11c551e078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'telegram_chat_id')
    # ### end Alembic commands ###
