"""empty message

Revision ID: 998e16f18441
Revises: 8782b2d39173
Create Date: 2024-07-14 23:18:38.301510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998e16f18441'
down_revision: Union[str, None] = '8782b2d39173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'created_at')
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('chats', 'created_at')
    op.drop_column('chats', 'updated_at')
    op.drop_column('gpt_settings', 'created_at')
    op.drop_column('gpt_settings', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'updated_at')
    op.drop_column('workers', 'created_at')
    op.drop_column('workers', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('gpt_settings', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('gpt_settings', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
