"""remove unused field


Revision ID: a77d819008d0
Revises: d1c34ed4fe39
Create Date: 2024-07-31 02:06:33.727763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77d819008d0'
down_revision: Union[str, None] = 'd1c34ed4fe39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
