"""names 

Revision ID: af8a611479c5
Revises: 1ca560c8f5b2
Create Date: 2024-09-03 14:32:59.382116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8a611479c5'
down_revision: Union[str, None] = '1ca560c8f5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('name', sa.String(), nullable=False))
    op.add_column('gpt_settings', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpt_settings', 'name')
    op.drop_column('campaigns', 'name')
    # ### end Alembic commands ###
