"""add service_prompt field

Revision ID: d0f0dc50fdbf
Revises: 13561cbf66de
Create Date: 2024-07-24 01:22:40.383588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f0dc50fdbf'
down_revision: Union[str, None] = '13561cbf66de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_settings', sa.Column('service_prompt', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpt_settings', 'service_prompt')
    # ### end Alembic commands ###
