"""Add field to worker and campaign

Revision ID: d1c34ed4fe39
Revises: d0f0dc50fdbf
Create Date: 2024-07-25 23:25:52.715949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c34ed4fe39'
down_revision: Union[str, None] = 'd0f0dc50fdbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('scope', sa.String()))
    op.add_column('workers', sa.Column('username', sa.String()))
    op.add_column('workers', sa.Column('bio', sa.String()))

    op.execute("UPDATE campaigns SET scope='default'")
    op.execute("UPDATE workers SET username='default'")
    op.execute("UPDATE workers SET bio='default'")

    op.alter_column('campaigns', 'scope', nullable=False)
    op.alter_column('workers', 'username', nullable=False)
    op.alter_column('workers', 'bio', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'bio')
    op.drop_column('workers', 'username')
    op.drop_column('campaigns', 'scope')
    # ### end Alembic commands ###
