"""worker.chats and dynamic fields

Revision ID: d205b178bf6b
Revises: 1abbcf5859b7
Create Date: 2024-09-25 21:41:31.913224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd205b178bf6b'
down_revision: Union[str, None] = '1abbcf5859b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('campaigns', sa.Column('type', sa.Enum('Native integration', 'Monitoring', native_enum=False), nullable=True))
    op.add_column('workers', sa.Column('chats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'chats')
    op.drop_column('campaigns', 'type')
    op.drop_column('campaigns', 'enabled')
    # ### end Alembic commands ###
