"""oprionals in chat

Revision ID: e2f12ec275a0
Revises: af8a611479c5
Create Date: 2024-09-06 19:27:44.834070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f12ec275a0'
down_revision: Union[str, None] = 'af8a611479c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chats', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chats', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chats', 'lead_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chats', 'lead_chat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'lead_chat_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chats', 'lead_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chats', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chats', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chats', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
