route:
  receiver: 'default-receiver'

receivers:
- name: 'default-receiver'
  telegram_configs:
    - send_resolved: true
      bot_token: "7085730278:AAFAPHZ8OSlX0Rk7TpPdi-iZB7ue_flo6sM"
      chat_id: "1269947715"
      parse_mode: "Markdown"
      message: "{{ template \"telegram.default.message\" . }}"
