route:
  group_by: ['alertname']
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'

receivers:
  - name: 'default-receiver'
    telegram_configs:
      - send_resolved: true
        bot_token: "7085730278:AAFAPHZ8OSlX0Rk7TpPdi-iZB7ue_flo6sM"
        chat_id: "4774607221"
        parse_mode: "Markdown"
        message: "{{ template \"telegram.default.message\" . }}"
  - name: 'critical-receiver'
    telegram_configs:
      - send_resolved: true
        bot_token: "7085730278:AAFAPHZ8OSlX0Rk7TpPdi-iZB7ue_flo6sM"
        chat_id: "1269947715"
        parse_mode: "Markdown"
        message: "{{ template \"telegram.critical.message\" . }}"
